config/routes.rb
Rails.application.routes.draw do
  
  
  get 'profiles/show'

  get 'progress/index'

  get 'progress/show'

  get 'assessments/new'

  get 'assessments/create'

  get 'assessments/index'

  get 'comments/index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'class_bookings/show'

  get 'class_bookings/index'

  get 'class_bookings/new'

  get 'class_bookings/create'

  get 'exercise_classes/show'

  get 'exercise_classes/index'

  

  resources :users 
  resources :profiles
      
  resources :trainers, controller: 'users', type: 'Trainer'
  resources :clients, controller: 'users', type: 'Client'

  resources :exercise_classes
  resources :articles 
  resources :comments
  resources :appointments
  resources :assessments
  resources :progress
  
  resources :class_bookings, only: [:create, :destroy]

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :conversations do
      resources :messages
    end
    
  root 'static_pages#home'

  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'signup'  =>  'users#new'
  get 'login'   =>  'sessions#new'
  post 'login'  =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'
  get 'newclass'  =>  'exercise_classes#new'
  get 'newarticle'  =>  'articles#new'
  get 'newappointment' => 'appointments#new'
  get 'articles'  =>  'articles#index'
  get 'allappointments' => 'appointments#index'
  get 'clientprogress' => 'progress#index'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@articles = Article.all
    #If the user is logged in retrieve upcoming appointments
    if logged_in? 
    @clientAppointments = current_user.appointments.upcoming.confirmed

    end
  end

  def help
  end

  def about
  	
  end


  def index

  	
  	
  end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_appointment_feed.html.erb
<% @clientAppointments.each do |appointment| %>
        
    <dl >
    	 <% if current_user.trainer? %>
      <dt><%= appointment.client.name%></dt>
      <% else %>
       <dt><%= appointment.trainer.name %></dt>
       <%end%>
       <dd><%= appointment.appointment_at.strftime("%B %d, %Y, %H:%M") %></dd>
      </dl>
                    
                
          
                        
 <% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About </h1>
<p>
	A college project for 4th year Software Systems Development, built by Daniel Kehoe
</p>


app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

	<h1>Help</h1>
	

app/views/static_pages/home.html.erb
<% if logged_in? %>
      
              <div class="row">
                <div class="col-xs-8 ">
                  <div class="panel panel-default box-shadow--6dp">
                    <div class="panel panel-body">
                      <h3><%= image_tag current_user.profile.avatar.url(:thumb)%>
                        <%= "Welcome #{current_user.first_name}" %></h3><br>
                      <% if current_user.appointments.any? %>
                      <div class="col-xs-6 ">
                      <h5><u>Your upcoming One to One Appointments</u></h5>
                      <%=render 'appointment_feed'%>
                      <%end %>
                      </div>
                      

                       <!--  if current_user.trainer? 
                      
                        button_to "New Article", newarticle_path, :method => "get", class: "btn btn-sm btn-primary"
                        end  -->
                      
                      </div>
                    </div>
                    <%=  image_tag ("clientsense.jpg"), :class=> "homeimg" %>
                </div>
              <div class="col-xs-4">
                     <%=render 'articles/article_feed'%>

                
                    <%= link_to "Go to Articles", articles_path, :method => "get",class: "btn btn-sm btn-primary" %>
                
                    
              </div>         
      </div>
              
      

    <% else %>
      <div class="center jumbotron">
        <h1>Welcome to ClientSense</h1>

        <h2>
          Demo application for ClientSense Client Management Software
          
        </h2>

        <!-- link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" -->
      </div>

      <%= link_to image_tag("rails.png", alt: "Rails logo"),
                  'http://rubyonrails.org/' %>
    <% end %>