config/routes.rb
Rails.application.routes.draw do
  
  
  get 'profiles/show'

  get 'progress/index'

  get 'progress/show'

  get 'assessments/new'

  get 'assessments/create'

  get 'assessments/index'

  get 'comments/index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'class_bookings/show'

  get 'class_bookings/index'

  get 'class_bookings/new'

  get 'class_bookings/create'

  get 'exercise_classes/show'

  get 'exercise_classes/index'

  

  resources :users 
  resources :profiles
      
  resources :trainers, controller: 'users', type: 'Trainer'
  resources :clients, controller: 'users', type: 'Client'

  resources :exercise_classes
  resources :articles 
  resources :comments
  resources :appointments
  resources :assessments
  resources :progress
  
  resources :class_bookings, only: [:create, :destroy]

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :conversations do
      resources :messages
    end
    
  root 'static_pages#home'

  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'signup'  =>  'users#new'
  get 'login'   =>  'sessions#new'
  post 'login'  =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'
  get 'newclass'  =>  'exercise_classes#new'
  get 'newarticle'  =>  'articles#new'
  get 'newappointment' => 'appointments#new'
  get 'articles'  =>  'articles#index'
  get 'allappointments' => 'appointments#index'
  get 'clientprogress' => 'progress#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :commentors, :through => :comments,:source => :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true







  
  # Retrieve all comments related to an article
	def discussion
        Comment.where("article_id = ?", id)
    end


    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#Check if user is logged in and restrict some actions for client
	before_filter :logged_in_user
	before_action :is_user_trainer, only: [:create, :edit, :uptate,:destroy]
	respond_to :html, :json

	def show
		@article = Article.find(params[:id])
		@comment  = current_user.comments.build
		#Retrieve article comments
		@discussion_comments = @article.discussion
		respond_to do |format|
        format.html {}
        format.json {render json: @article}
        
        end

	end

	def index
		@articles = Article.all
		respond_to do |format|
        format.html {@articles}
        format.json {render json: @articles}
        
        end
	end

	def create		
		#Create article related to author
		 @article = current_user.articles.build(secure_article) 
			 if @article.save
			    flash[:success] = "Posted Article"
			          redirect_to @article
			  else
			        	render 'new'
			  end		
		
  	  	
	end



	def new
			is_user_trainer
			@article = Article.new
	end


	def edit
    @article = Article.find(params[:id])
    end

	def update
	    @article = Article.find(params[:id])
	    if @article.update_attributes(secure_article)
	       flash[:success] = "Article Updated"
	       redirect_to article_path
	    else
	      render action: "edit"
	    end
	end


	def destroy
		Article.find(params[:id]).destroy
    		flash[:success] = "Article deleted"
    		redirect_to articles_path
            
            
    end



    private
    #article params
    def secure_article
    	params.require(:article).permit(:title,:content,:commentable)
    end
    #check if the user is trainer
    def is_user_trainer
         unless current_user.trainer?
         	redirect_to(root_url)
        	flash[:danger] = "You do not have permission to view this page"
        end
    end 



end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_feed.html.erb

  <div class="panel panel-default box-shadow--6dp">
     <div class="panel panel-body">
              <p><h4>Recent Articles</h4></p>
              <hr>
                  
                    <% @articles.each do |article| %>
                            
                        <dl >
                          <dt><%= link_to article.title, article%></dt>
                           <dd><%= sanitize(truncate(article.content, length: 100,  escape: false))%></dd>
                          </dl>
                         <hr>                
                                    
                              
                                            
                     <% end %>

</div>
</div>

app/views/articles/_articleform.html.erb
<%= form_for @article do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :title %>
                
      <%= f.text_field :title ,{class: 'form-control' }%>
                
      <%= f.label :content %>
                
      <%= f.cktext_area :content, rows: 10, :ckeditor => {:toolbar => 'mini'}   %><br>
                
      <%= f.label :commentable, 'Allow comments'.html_safe  , {class: ""} %>
      <%= f.check_box (:commentable), {class: 'checkbox'}%>
      <div class = "row">
        <div class = "col-md-3 col-md-push-9">
     <%= f.submit yield(:button_text), class: "btn btn-success" %>
        </div>
     </div>
 
<% end %>

            

app/views/articles/edit.html.erb
<h1><%= "Editing #{@article.title}" %></h1>
<% provide(:button_text, 'Update Article') %>
<div class="row">
   <div class="col-md-10 col-md-push-1">
		<%= render "articleform" %>
   </div>
</div>

app/views/articles/index.html.erb
<h1 align="left">Articles</h1>

<% if current_user.trainer? %>
<div class="row">
  <div class="col-md-3">
      <%= link_to "New Article", newarticle_path, :method => "get", class: "btn btn-sm btn-success" %>
  </div>
</div>
<% end %>
<br>
      <div class="row">
        <div class="col-md-12">
        <% @articles.each do |article| %>
         <div class="panel panel-default box-shadow--6dp">
         <div class="panel-body ">     
          <div class="col-md-11">
            <h3><%= link_to article.title, article%></h3>
            <i><%= article.user.name%></i><br>
            <i><%= article.user.created_at.strftime("%B %d, %Y")%></i><br><br>
            <p><%= sanitize(truncate(article.content, length: 300,  escape: false))%></p>
            
            
          </div>
          <div class="col-md-1">
            <% if current_user.trainer? %>
              <div class="btn-group">
                <%= button_to " Edit", edit_article_path(article), method: :get, class: "btn-primary" %>
                <%= button_to "Delete", article_path(article.id), method: :delete, data: { confirm: "You sure?" }, class: "btn-primary" %>
              </div>
            <% end %> 
          </div>
        </div>
        </div>
        <% end %>
      </div>
      </div>







 




app/views/articles/new.html.erb
<% provide(:title, 'Article Entry') %>
<% provide(:button_text, 'Publish Article') %>
<h1>Create Article</h1>

<div class="row">
   <div class="col-md-10 col-md-push-1">     

                <%= render "articleform" %>     
        
      </div>
    </div>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
    <div class="row">
         <div class="col-md-10 col-md-push-1">                   
            <h1> <%= @article.title%> </h1>
              <div class="panel panel-default box-shadow--6dp">
                <div class="panel panel-body">
                  <%= simple_format(@article.content) %>
                </div>
                <div class="panel-footer"><%= @article.user.name %>
                </div>
              </div>                   
                <%if @article.commentable? %>
                    <%= render 'shared/comment_form' %> <hr>                    	 
                  <h3>Comments</h3>
                    <%= render 'shared/discussion' %>    
                <%end%>
          </div>
    </div>



        