config/routes.rb
Rails.application.routes.draw do
  
  
  get 'profiles/show'

  get 'progress/index'

  get 'progress/show'

  get 'assessments/new'

  get 'assessments/create'

  get 'assessments/index'

  get 'comments/index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'class_bookings/show'

  get 'class_bookings/index'

  get 'class_bookings/new'

  get 'class_bookings/create'

  get 'exercise_classes/show'

  get 'exercise_classes/index'

  

  resources :users 
  resources :profiles
      
  resources :trainers, controller: 'users', type: 'Trainer'
  resources :clients, controller: 'users', type: 'Client'

  resources :exercise_classes
  resources :articles 
  resources :comments
  resources :appointments
  resources :assessments
  resources :progress
  
  resources :class_bookings, only: [:create, :destroy]

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :conversations do
      resources :messages
    end
    
  root 'static_pages#home'

  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'signup'  =>  'users#new'
  get 'login'   =>  'sessions#new'
  post 'login'  =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'
  get 'newclass'  =>  'exercise_classes#new'
  get 'newarticle'  =>  'articles#new'
  get 'newappointment' => 'appointments#new'
  get 'articles'  =>  'articles#index'
  get 'allappointments' => 'appointments#index'
  get 'clientprogress' => 'progress#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	# STI 
	self.inheritance_column = :type


	has_many :exercise_classes, dependent: :destroy
	has_many :class_bookings
	has_many :attendances, :through => :class_bookings, :source => :exercise_class 
	has_many :articles, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :conversations, :foreign_key => :sender_id
	has_one :profile
	# STI scope
	scope :trainers, -> { where(type: 'Trainer') }
	scope :clients, -> { where(type: 'Client') }

	validates :name, presence: true, length: {in: 4..30}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
			format: {with: VALID_EMAIL_REGEX},
			uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true
	#validates :password_confirmation, presence: true
	has_secure_password

	before_save {|user| user.email = email.downcase}
	self.per_page = 5
	# Create profile when user is created
	after_create :create_profile
	
	def to_partial_path
  		'users/user'
	end 


	#Returns the hash digest of a string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt:: Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	#Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Remembers a suer in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	#returns true if the given token matches the digest.
	def authenticated?(remember_token)
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	#forgets a user
	def forget
		update_attribute(:remember_digest, nil)
	end
	# Cehck if a user is attending a group exercise class
	def attending?(exerciseclass)
    	exerciseclass.participants.include?(self)
  	end

  	# Creates a class booking for the current user
	def attend!(exerciseclass)
    	self.class_bookings.create!(exercise_class_id: exerciseclass.id)
  	end

  	# Cancels a class booking for the current user
  	def cancel!(exerciseclass)
    	self.class_bookings.find_by(exercise_class_id: exerciseclass.id).destroy
  	end

  	# Splits the users name to retrieve first name
  	def first_name
    self.name.blank? ? "" : self.name.split(" ")[0]
  end

  	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :logged_in_user
  before_action :logged_in_user, only: [:read,:edit, :edit,:update]
  before_action :correct_user,   only: [:edit, :update]
  respond_to :html, :json

	def show
    #On the users profile page retrieve their group class attendances, if trainer their created classes, and users profile
        logged_in_user
        @user = User.find(params[:id])
        @bookings = @user.attendances
        @createdclasses = @user.exercise_classes
        @profile = @user.profile

        respond_to do |format|
        format.html {@user}
        format.js {@user}
        format.json {render json: @user.to_json}
      end
       # @articles = @user.articles.paginate(page: params[:page])
      end

  def index  
      #If the user is logged in on index retrieve users converations, and trainers and clients to display 
      if !logged_in?
        redirect_to login_url
        else
          @users = User.all.where.not(id: current_user.id).paginate(page: params[:page])
          @conversations = Conversation.involving(current_user).order("created_at DESC")
          @trainers = User.trainers.where.not(id: current_user.id).paginate(page: params[:page])
          @clients = User.clients.where.not(id: current_user.id).paginate(page: params[:page])

          respond_to do |format|
            format.html {@users}
            format.json {render json: @users}
          end               
                  
                  
        end     
end

      
  def new
  	@user = User.new
    @user.type = params[:user_type]
  end





  def create
  	@user = User.new(user_params)
  	if @user.save
      remember @user
      flash[:success] = "Welcome !"   
  		redirect_to @user
  	   else
		        render 'new'

	   end
  end

  def edit
    @user = User.find(params[:id])
  end

   def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end



  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  #Unused method 
  def change_type
    @user = User.find(params[:id])
    @user
    if @user.save
      flash[:success] = "Account updated"
      redirect_to users_url
      else
        flash[:success] = "Account not updated"
      redirect_to users_url
    end
  end





  private
    #User parameters
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation,:type)
    end


    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    #Check if user is correct so only edit own info
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    def user_type
      params[:type].capitalize
    end

    def sti_type_is_trainer
      if self.type? == 'Trainer'
        true
      else
        false
      end
    end


    



end

app/helpers/users_helper.rb
module UsersHelper

       # Returns the Gravatar (http://gravatar.com/) for the given user.
      def gravatar_for(user, options = { size: 50 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end 

  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end

    end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.select :type, options_for_select([["Client"], ["Trainer"]]) %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <!-- gravatar_for user, size: 50  -->
  <h5><%= link_to user.name, user  %></h5><p>
  <% if current_user.trainer? && !current_user?(user) %>
   <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "You sure?" },
                                  class: "btn btn-danger btn-xs"%>   
    
  <% end %>
  | <%= link_to "Message", "#", class: "btn btn-default btn-xs start-conversation",
                    "data-sid" => current_user.id, "data-rip" => user.id %> </p>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>


app/views/users/index.html.erb

<h1>All users</h1>
<div class = "row">
<div class="col-xs-4">
  <div class="panel panel-default box-shadow--6dp">
      <div class="panel panel-body">
                  
                          
        <ul class="users">
          <h3>Clients</h3>
          <%= render @clients %>
        </ul>
        <%= will_paginate %>
      </div>
    </div>

</div>
<div class="col-xs-4">
  <div class="panel panel-default box-shadow--6dp">
      <div class="panel panel-body">
                  
                          
        <ul class="users">
          <h3>Trainers</h3>
          <%= render @trainers %>
        </ul>
        <%= will_paginate %>
      </div>
    </div>

</div>

<div class="col-xs-4">
  <div class="panel panel-default box-shadow--6dp">
      <div class="panel panel-body">
    <h3><%= "#{current_user.first_name}" %>'s Conversations</h3>

    <div style="height: 400px; overflow-y: auto;">
      <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>   
                <li class="media">
                  <%= image_tag(conversation_interlocutor(conversation).profile.avatar.url(:thumb), class: "media-object pull-left") %>
                  <div class="media-body">
                    <%= link_to "Open", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id %>
                    | <%= link_to "Delete", conversation, method: :delete, data: { confirm: "You sure?" } %>
                        <h4 class="media-heading"><%= conversation_interlocutor(conversation).name %></h4>
                        <p><%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                  </div>
                </li>

            <% end %>
          </ul>
      <% else %>
          <p>You have no current conversations.</p>
      <% end %>
    </div>
</div>
</div>
</div>
  </div>

  <div class="col-md-4">

  </div>




app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
       <section class="user_info">
          <h1>            
            <%= @user.name %>           
          </h1>
        </section>
      <div class="row">
    <div class="col-xs-8">      
      <%=render 'profiles/show'%>
    </div>  
      <div class="col-xs-4">
          <div class="panel panel-default box-shadow--6dp">
               <div class="panel panel-body">
                        <% if (@user.trainer?)%>
                            <h5><%= "#{@user.first_name}" %>'s Group Classes</h5> 
                            <% @createdclasses.each do |exclass| %><br><hr>
                            <%= link_to exclass.title, exclass %>
                            <%end%>                            
                       <% else%>
                          <h5><%= "#{@user.first_name}" %> is Attending</h5>
                          <% @bookings.each do |exclass| %><br><hr>
                          <%= link_to exclass.title, exclass %>
                          <%end%>
                      <%end%>
          </div>
          </div>
</div>
 <%if !current_user.trainer? and current_user == @user%>
    <%= link_to "View Progress", clientprogress_path, :method => "get", class: "btn btn-sm btn-primary" %>            
 <%end%>

      </div>

      <div id="profile-modal" class="modal fade"></div>