config/routes.rb
Rails.application.routes.draw do
  
  
  get 'profiles/show'

  get 'progress/index'

  get 'progress/show'

  get 'assessments/new'

  get 'assessments/create'

  get 'assessments/index'

  get 'comments/index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'class_bookings/show'

  get 'class_bookings/index'

  get 'class_bookings/new'

  get 'class_bookings/create'

  get 'exercise_classes/show'

  get 'exercise_classes/index'

  

  resources :users 
  resources :profiles
      
  resources :trainers, controller: 'users', type: 'Trainer'
  resources :clients, controller: 'users', type: 'Client'

  resources :exercise_classes
  resources :articles 
  resources :comments
  resources :appointments
  resources :assessments
  resources :progress
  
  resources :class_bookings, only: [:create, :destroy]

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :conversations do
      resources :messages
    end
    
  root 'static_pages#home'

  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'signup'  =>  'users#new'
  get 'login'   =>  'sessions#new'
  post 'login'  =>  'sessions#create'
  delete 'logout' =>  'sessions#destroy'
  get 'newclass'  =>  'exercise_classes#new'
  get 'newarticle'  =>  'articles#new'
  get 'newappointment' => 'appointments#new'
  get 'articles'  =>  'articles#index'
  get 'allappointments' => 'appointments#index'
  get 'clientprogress' => 'progress#index'

end

app/controllers/exercise_classes_controller.rb
class ExerciseClassesController < ApplicationController
  #Check if user is logged in and restrict some actions for client
  before_filter :logged_in_user
  before_action :is_user_trainer, only: [:create, :edit, :uptate,:destroy]
  respond_to :html, :json
  
  def show
  	@exerciseclass = ExerciseClass.find(params[:id])
  end

  def index

  	@exerciseclasses = ExerciseClass.all
    #Using scope from the model to find classes upcoming
    @classes_upcoming = ExerciseClass.upcoming.paginate(page: params[:upcoming])
    @classes_past = ExerciseClass.past.paginate(page: params[:past])

    respond_to do |format|

          format.html {@classes_upcoming}
          format.js {@classes_upcoming}
    end

  end

  def create
  	#Build exercise class related to trainer who creates it
        @exerciseclass = current_user.exercise_classes.build(secure_exclass) 
        @classes_upcoming = ExerciseClass.upcoming.paginate(page: params[:upcoming])        

        respond_to do |format|
          if @exerciseclass.save
            format.html {redirect_to exercise_classes_path}
            format.json { head :no_content }
            format.js

          else          
            format.html 
            format.json { render json: @exerciseclass.errors.full_messages, status: :unprocessable_entity }
            format.js{@exerciseclass.errors.full_messages}
            
          end
        end  	
  end


  def new
    is_user_trainer
  	@exerciseclass = ExerciseClass.new
    
  end

  def update
      @exerciseclass = ExerciseClass.find(params[:id])
      #if @exerciseclass.update_attributes(secure_exclass)
         #flash[:success] = "Class Updated"
         #redirect_to @exerciseclass
     # else
        #render action: "edit"
      #end
      
      respond_to do |format|
          if @exerciseclass.update_attributes(secure_exclass)
            format.html {redirect_to @exerciseclass}
            format.json { head :no_content }
            format.js

          else          
            
            format.json { render json: @exerciseclass.errors.full_messages, status: :unprocessable_entity }
            format.js{@exerciseclass.errors.full_messages}
            end
          end
  end


  def edit
    @exerciseclass = ExerciseClass.find(params[:id])
  end

  def destroy

    ExerciseClass.find(params[:id]).destroy
        flash[:success] = "Class deleted"
        redirect_to exercise_classes_path
                  
 end

#exercise class params
 def secure_exclass
      params.require(:exercise_class).permit(:title,:description,:class_style_id,:class_level_id,:date,:image)
 end


 def is_user_trainer
         unless current_user.trainer?
          redirect_to(root_url)
          flash[:danger] = "You do not have permission to view this page"
        end
    end 


end

app/helpers/exercise_classes_helper.rb
module ExerciseClassesHelper
end

app/views/exercise_classes/_cancel.html.erb
<%= form_for(current_user.class_bookings.find_by(exercise_class_id: @exerciseclass.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Cancel", class: "btn btn-large" %>
<% end %>

app/views/exercise_classes/_classform.html.erb
 <div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @exerciseclass, remote: true, html: {  style: "display:inline;", multipart: true, } do |f| %>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Class</h4>
      </div>
      <div class="modal-body">
        <ul class="errors"></ul>

 <!-- form_for(@exerciseclass) do |f|  -->
       <!-- render 'shared/error_messages', object: f.object  -->
          <%= f.label :title %>
          <%= f.text_field :title ,{class: 'form-control' }%>

          <%= f.label :description %>
          <%= f.text_area :description ,{class: 'form-control' }%>

          <%= f.label :class_style %><br />
          <%= f.collection_select(:class_style_id, ClassStyle.all, :id, :style, {}, {class: 'form-control' } ) %>

          <%= f.label :class_level %><br>
          <%= f.collection_radio_buttons(:class_level_id, ClassLevel.all, :id, :level, {}, {class: 'radio' }    ) %><br>

          <%= f.label :date %>
          <div class="input-group date" class="datetimepicker">
                    <%= f.datetime_field :date, class: 'form-control datetimepicker'%>
                      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                    <script type="text/javascript"> /*Datetime picker with disabled hours and days*/
                      $(function(){
                        $('.datetimepicker').datetimepicker({
                        daysOfWeekDisabled: [0],
                        disabledHours: [0, 1, 2, 3, 4, 5, 6, 22, 23, 24],
                        format: 'DD-MM-YYYY HH:mm',
                        useCurrent: false,
                        });
                       });
                    </script>   

          <%= f.label :image %>
          <%= f.file_field :image %>
            
          <!-- <div class="row">
               <div class="col-md-6 col-md-offset-3">
                     f.submit yield(:button_text), class: "btn btn-success" 
               </div>
          </div> -->



 </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>






          

app/views/exercise_classes/_edit.html.erb
<%= render "classform" %>

app/views/exercise_classes/_index.html.erb
<% @classes_upcoming.each do |exclass| %>
	<div class="panel panel-info box-shadow--6dp" >
		<div class="panel-heading">
			<h3 class="panel-title"><%= link_to exclass.title, exclass%></h3>
				</div>
					<div class="panel-body">					
						    <div class="row">
						      <div class="col-xs-4">
						        <%=  link_to (image_tag exclass.image.url(:thumb)), exclass %>

						      </div>
						      <div class="col-xs-8">
						        <b><%= exclass.class_style.style%></b><br>
						        <p><%=  exclass.class_level.level%></p>
						        <%=  exclass.date.strftime("%B %d, %Y, %H:%M") %>
						      </div>
						    </div>
						  
					</div>
								  
	</div>
<% end %>

app/views/exercise_classes/_save.js.erb
$("ul.errors").html("")
<% if @exerciseclass.errors.any? %>
  <% @exerciseclass.errors.full_messages.each do |message| %>
  
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#class-index").html("<%= escape_javascript(render 'index') %>")
  $("#class-modal").modal("hide")
<% end %>

app/views/exercise_classes/_save_edit.js.erb
$("ul.errors").html("")
<% if @exerciseclass.errors.any? %>
  <% @exerciseclass.errors.full_messages.each do |message| %>
  
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#class-show").html("<%= escape_javascript(render 'show') %>")
  $("#class-modal").modal("hide")
<% end %>

app/views/exercise_classes/_show.html.erb
<div class="row">
    <div class="col-md-9 ">

        <div class="panel panel-info box-shadow--6dp">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @exerciseclass.title%></h3>
            </div>
                <div class="panel-body">
                    <p><%=  image_tag @exerciseclass.image.url(:large), :class=> "eximg" %></p>
                    <p> <%= @exerciseclass.description %></p>
                     <p><%= @exerciseclass.class_style.style %></p>
                     <p><%= @exerciseclass.class_level.level %></p>
                     <p><%= @exerciseclass.date.strftime("%B %d, %Y, %H:%M") %></p>
                     <p><%= @exerciseclass.user.name %><br>
                </div>
        </div>
  </div>
  <div class="col-md-3 ">
        <% if current_user.trainer? %>
          <div>
                    <%= button_to "Edit", edit_exercise_class_path(@exerciseclass), remote: true, method: :get, class: "btn btn-sm btn-primary " %><br>
          </div>
          <div>
                    <%= button_to "Delete", @exerciseclass, method: :delete, data: { confirm: "You sure?" } ,class: "btn btn-sm btn-primary " %><br>
          </div>
        <%end%>
        <div class="panel panel-default box-shadow--6dp">
            <div class="panel-heading">
              <h1 class="panel-title"><h4> Attending</h1>
            </div>
            <ul>
                <% @exerciseclass.participants.each do |attendee| %>
                <div class="panel-body">
                  <li><%= link_to attendee.name, attendee %></li>
                </div>
                <% end %>
            </ul>
        </div>
    </div>


 </div>
<% unless current_user.trainer? %> 
 <div class="row">
      <div class="col-md-3 col-xs-push-6">
        <% unless @exerciseclass.date.past? %>   
            <%= render 'attend_form' %>
        <%end%>
        </div>

</div>
<%end%>     

app/views/exercise_classes/create.js.erb
<%= render "save" %>

app/views/exercise_classes/edit.html.erb
<% provide(:title, 'Exercise Class Entry') %>
<h1><%= "Editing #{@exerciseclass.title}" %></h1>
<% provide(:button_text, 'Update Class') %>

<div class="row">
      
        <div class="col-md-6 col-md-offset-3">
              <div class = "panel panel-default">
                  <div class = "panel-body">       
                    <%= render 'classform'%>
                  </div>
              </div>
        </div>
         
        
      </div>
    </div>

app/views/exercise_classes/edit.js.erb
$("#class-modal").html("<%= escape_javascript(render 'edit') %>")
$("#class-modal").modal("show")

app/views/exercise_classes/index.html.erb
<h1>Group Classes</h1>
				<div class="row">
					<div class="col-md-3 col-xs-push-1">
						 <% if current_user.trainer? %>
						 <%= link_to "New Class", new_exercise_class_path, remote: true, method: :get, class: "btn btn-sm btn-success" %>
						 <%end%>
					</div>
				</div>
						<div class="row" id="list">
					 		<div class="col-xs-10 col-xs-push-1">
					 			<div id="class-index">
					 					<h3></h3>
										<%= render 'index'%>
										<%= will_paginate @classes_upcoming, :param_name => "upcoming" %>						

								</div>		 
					 		</div>
					 	</div>
  
<div id="class-modal" class="modal fade"></div>

app/views/exercise_classes/new.html.erb
<h1>Create New Class</h1>

<% provide(:title, 'Exercise Class Entry') %>
<% provide(:button_text, 'Add Class') %> 
      <div class="row">

            <div class="col-md-6 col-md-offset-3">
              <div class = "panel panel-default">
                  <div class = "panel-body">
              
                      <%= render 'classform'%>

                  </div>
            </div>
          </div>
      </div>









app/views/exercise_classes/new.js.erb
$("#class-modal").html("<%= escape_javascript(render 'new') %>")
$("#class-modal").modal("show")

app/views/exercise_classes/update.js.erb
<%= render "save_edit" %>